-- 0049: the cloud and the outlet each prove the other is there, every five seconds
--
-- FR-EDG-023 is the most numerically specific requirement in Phase 1, and the numbers are
-- the requirement: a signed bidirectional challenge every 5 seconds, degraded at 10, the
-- cloud's forwarding lease expired at 20, and resumption only after THREE consecutive
-- valid proofs.
--
-- WHY BIDIRECTIONAL IS NOT A FLOURISH. A node that can hear the cloud but cannot be heard
-- is not reachable, and it is the more dangerous half: the cloud believes it is talking to
-- an outlet that is not receiving, and keeps forwarding commands into a hole. So one
-- exchange carries BOTH directions and a failure in either expires the lease. Half a proof
-- is not three-quarters of a proof; it is a failed one.
--
-- WHAT A PROOF CARRIES. FR-EDG-023 names five things and all five are checked together,
-- because any one of them being stale makes the other four a description of a peer that is
-- no longer there:
--
--   1. cloud-to-node reachability      the challenge arrived
--   2. node-to-cloud reachability      the response got back
--   3. the same monotonic authority    both agree who may write        (0050 defines it)
--   4. protocol compatibility          both speak a version the other understands
--   5. cursor posture                  neither is further ahead than the other believes
--
-- WHOSE LEASE IT IS. The thing that expires is the CLOUD'S permission to forward commands
-- to the outlet. The outlet does not stop trading when it expires — that is M5a's whole
-- point and FR-EDG-021 says so in as many words. What stops is the cloud acting as though
-- it can reach an authority it cannot.
--
-- THREE PROOFS TO COME BACK, ONE TO GO DOWN. Deliberately asymmetric, and the asymmetry is
-- the safety: a flapping link produces occasional valid proofs, and a lease that resumed on
-- the first of them would flap with it. Coming back is the direction where being slow is
-- safe.
--
-- WHAT "SIGNED" MEANS HERE, SAID PLAINLY. The same bound 0048 records: this database has
-- no pgcrypto, so a proof is a KEYED DIGEST over the challenge and the node's trust anchor
-- rather than a signature. It shows the responder knew the anchor. It does not show who
-- they were. planning/M5B_FINDINGS.md carries that with what closes it.

-- ---------------------------------------------------------------------------
-- 1. VOCABULARY
-- ---------------------------------------------------------------------------

CREATE TYPE edge.proof_direction AS ENUM ('cloud_to_node', 'node_to_cloud');

CREATE TYPE edge.lease_state AS ENUM ('live', 'degraded', 'expired');

-- ---------------------------------------------------------------------------
-- 2. THE NUMBERS, IN ONE PLACE
-- ---------------------------------------------------------------------------

CREATE TABLE edge.lease_policy (
    tenant_id uuid NOT NULL,
    outlet_id uuid NOT NULL,

    proof_interval_seconds    integer NOT NULL DEFAULT 5,
    degrade_after_seconds     integer NOT NULL DEFAULT 10,
    expire_after_seconds      integer NOT NULL DEFAULT 20,
    proofs_required_to_resume integer NOT NULL DEFAULT 3,

    CONSTRAINT lease_policy_pkey PRIMARY KEY (tenant_id, outlet_id),
    CONSTRAINT lease_policy_outlet_fk FOREIGN KEY (tenant_id, outlet_id)
        REFERENCES org.org_node (tenant_id, id) ON DELETE RESTRICT,

    -- THE ORDER OF THE THRESHOLDS IS A RULE, NOT A CONVENTION. A policy that expired
    -- before it degraded would skip the state an operator is meant to notice, and a
    -- degrade threshold below the proof interval would degrade a healthy link between
    -- two proofs that both arrived on time.
    CONSTRAINT lease_policy_thresholds_ascend CHECK (
        proof_interval_seconds < degrade_after_seconds
    AND degrade_after_seconds < expire_after_seconds),
    CONSTRAINT lease_policy_resume_is_more_than_one CHECK (proofs_required_to_resume >= 2)
);

COMMENT ON TABLE edge.lease_policy IS
    'FR-EDG-023''s four numbers, per outlet. Defaults rather than constants because the '
    'requirement says "by default", and an outlet on a satellite link is why it does. '
    'They ascend by CHECK: a lease that expired before it degraded would skip the state '
    'an operator is supposed to act on.';

ALTER TABLE edge.lease_policy ENABLE ROW LEVEL SECURITY;
ALTER TABLE edge.lease_policy FORCE ROW LEVEL SECURITY;
CREATE POLICY lease_policy_isolation ON edge.lease_policy FOR ALL
    USING (app.row_in_scope(tenant_id, outlet_id))
    WITH CHECK (app.row_in_scope(tenant_id, outlet_id));

-- ---------------------------------------------------------------------------
-- 3. THE PROOFS
-- ---------------------------------------------------------------------------

CREATE TABLE edge.reachability_proof (
    id        bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tenant_id uuid NOT NULL,
    outlet_id uuid NOT NULL,
    node_id   uuid NOT NULL,

    -- BOTH DIRECTIONS SHARE A CHALLENGE, which is what makes them one proof rather than
    -- two observations that happened to be near each other in time.
    challenge       character(64) NOT NULL,
    direction       edge.proof_direction NOT NULL,
    response_digest character(64) NOT NULL,

    authority_sequence  bigint  NOT NULL,
    protocol_compatible boolean NOT NULL,
    cursor_agrees       boolean NOT NULL,
    valid               boolean NOT NULL,
    detail              text,

    observed_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT reachability_proof_node_fk FOREIGN KEY (tenant_id, node_id)
        REFERENCES edge.node (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT reachability_proof_outlet_fk FOREIGN KEY (tenant_id, outlet_id)
        REFERENCES org.org_node (tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT reachability_proof_one_per_direction UNIQUE (node_id, challenge, direction),
    CONSTRAINT reachability_proof_sequence_positive CHECK (authority_sequence >= 0),

    -- AN INVALID PROOF SAYS WHY. This is the table an operator reads after an outage, and
    -- a failure recorded with no reason is a fact nobody can act on.
    CONSTRAINT reachability_proof_failure_is_explained CHECK (valid OR detail IS NOT NULL),

    -- AND A VALID ONE CANNOT DISAGREE WITH ITSELF. `valid` is a conclusion, not a fifth
    -- independent field: if the protocol is incompatible or the cursors disagree then the
    -- proof is not valid, whatever the caller passed.
    CONSTRAINT reachability_proof_validity_follows_its_parts CHECK (
        NOT valid OR (protocol_compatible AND cursor_agrees))
);

COMMENT ON TABLE edge.reachability_proof IS
    'FR-EDG-023. One exchange is two rows sharing a challenge, one per direction. A node '
    'that can hear the cloud but cannot be heard is not reachable, and it is the more '
    'dangerous half — the cloud keeps forwarding into a hole.';

CREATE INDEX reachability_proof_recent_idx
    ON edge.reachability_proof (node_id, observed_at DESC);

CREATE TRIGGER reachability_proof_is_append_only
    BEFORE UPDATE OR DELETE ON edge.reachability_proof
    FOR EACH ROW EXECUTE FUNCTION app.refuse_financial_mutation();

ALTER TABLE edge.reachability_proof ENABLE ROW LEVEL SECURITY;
ALTER TABLE edge.reachability_proof FORCE ROW LEVEL SECURITY;
CREATE POLICY reachability_proof_isolation ON edge.reachability_proof FOR ALL
    USING (app.row_in_scope(tenant_id, outlet_id))
    WITH CHECK (app.row_in_scope(tenant_id, outlet_id));

-- ---------------------------------------------------------------------------
-- 4. THE LEASE
-- ---------------------------------------------------------------------------

CREATE TABLE edge.forwarding_lease (
    tenant_id uuid NOT NULL,
    outlet_id uuid NOT NULL,
    node_id   uuid NOT NULL,

    state edge.lease_state NOT NULL DEFAULT 'expired',

    -- The last exchange in which BOTH directions were valid. Not "the last proof": a
    -- single direction arriving proves half of something.
    last_complete_exchange_at timestamptz,
    consecutive_valid_exchanges integer NOT NULL DEFAULT 0,

    state_changed_at timestamptz NOT NULL DEFAULT now(),
    state_reason     text NOT NULL,

    CONSTRAINT forwarding_lease_pkey PRIMARY KEY (node_id),
    CONSTRAINT forwarding_lease_tenant_id_unique UNIQUE (tenant_id, node_id),
    CONSTRAINT forwarding_lease_node_fk FOREIGN KEY (tenant_id, node_id)
        REFERENCES edge.node (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT forwarding_lease_outlet_fk FOREIGN KEY (tenant_id, outlet_id)
        REFERENCES org.org_node (tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT forwarding_lease_counter_not_negative CHECK (consecutive_valid_exchanges >= 0),
    CONSTRAINT forwarding_lease_reason_is_stated CHECK (length(trim(state_reason)) > 0),

    -- A LIVE LEASE HAS SEEN A COMPLETE EXCHANGE. Starting life live with nothing behind it
    -- would be the cloud forwarding on the strength of never having checked.
    CONSTRAINT forwarding_lease_live_has_evidence CHECK (
        state <> 'live' OR last_complete_exchange_at IS NOT NULL)
);

COMMENT ON TABLE edge.forwarding_lease IS
    'FR-EDG-023. The CLOUD''S permission to forward commands to this outlet, and nothing '
    'else. When it expires the outlet keeps trading — FR-EDG-021 requires that — and what '
    'stops is the cloud acting as though it can reach an authority it cannot. It begins '
    'expired: a lease that started live would be forwarding on the strength of never '
    'having checked.';

ALTER TABLE edge.forwarding_lease ENABLE ROW LEVEL SECURITY;
ALTER TABLE edge.forwarding_lease FORCE ROW LEVEL SECURITY;
CREATE POLICY forwarding_lease_isolation ON edge.forwarding_lease FOR ALL
    USING (app.row_in_scope(tenant_id, outlet_id))
    WITH CHECK (app.row_in_scope(tenant_id, outlet_id));

-- ---------------------------------------------------------------------------
-- 5. WHAT A RESPONDER MUST PRESENT
-- ---------------------------------------------------------------------------

-- Exposed so one construction is used by the check, the suite and an operator. A test that
-- re-derived it would be agreeing with itself. Same shape and the same bound as
-- edge.update_attestation(): a keyed digest, not a signature.
CREATE FUNCTION edge.proof_response(p_challenge     character(64),
                                    p_trust_anchor  character(64),
                                    p_direction     edge.proof_direction)
RETURNS character(64)
LANGUAGE sql IMMUTABLE
SET search_path TO 'pg_catalog', 'public'
AS $$
    SELECT encode(sha256((p_challenge || p_trust_anchor || p_direction::text)::bytea),
                  'hex')::character(64);
$$;

COMMENT ON FUNCTION edge.proof_response(character, character, edge.proof_direction) IS
    'The response a peer must present. The DIRECTION is inside the digest, so a response '
    'proving one direction cannot be replayed as the other — which is the whole content '
    'of "bidirectional". Not a signature: no pgcrypto here, so it shows the responder knew '
    'the anchor and not who they were.';

-- ---------------------------------------------------------------------------
-- 6. RECORDING ONE HALF OF AN EXCHANGE
-- ---------------------------------------------------------------------------

CREATE FUNCTION edge.record_proof(
    p_tenant_id uuid,
    p_node_id   uuid,
    p_challenge character(64),
    p_direction edge.proof_direction,
    p_response  character(64),
    p_authority_sequence bigint,
    p_protocol_compatible boolean,
    p_cursor_agrees boolean)
RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'pg_catalog', 'edge', 'public'
AS $$
DECLARE
    n edge.node%ROWTYPE;
    v_expected character(64);
    v_valid    boolean;
    v_detail   text;
BEGIN
    SELECT * INTO n FROM edge.node
      WHERE tenant_id = p_tenant_id AND id = p_node_id AND status = 'active';
    IF NOT FOUND THEN
        RAISE EXCEPTION 'NODE_UNKNOWN: no active node % for this tenant', p_node_id
            USING ERRCODE = 'HS404';
    END IF;

    v_expected := edge.proof_response(p_challenge, n.update_trust_anchor_sha256, p_direction);

    -- EVERY REASON IT COULD FAIL, GATHERED RATHER THAN SHORT-CIRCUITED. An operator
    -- reading this row after an outage wants to know whether the peer was unreachable,
    -- speaking the wrong protocol, or behind on its cursor — and short-circuiting on the
    -- first would tell them only the first.
    v_detail := NULLIF(concat_ws('; ',
        CASE WHEN p_response <> v_expected
             THEN 'the response does not match the challenge and this node''s anchor' END,
        CASE WHEN NOT p_protocol_compatible
             THEN 'the peer''s protocol version is out of range' END,
        CASE WHEN NOT p_cursor_agrees
             THEN 'the peer''s cursor disagrees with this node''s' END), '');
    v_valid := v_detail IS NULL;

    INSERT INTO edge.reachability_proof (
        tenant_id, outlet_id, node_id, challenge, direction, response_digest,
        authority_sequence, protocol_compatible, cursor_agrees, valid, detail)
    VALUES (p_tenant_id, n.outlet_id, p_node_id, p_challenge, p_direction, p_response,
            p_authority_sequence, p_protocol_compatible, p_cursor_agrees, v_valid, v_detail);

    RETURN v_valid;
END;
$$;

-- ---------------------------------------------------------------------------
-- 7. WHAT THE PAIR OF THEM MEANS
-- ---------------------------------------------------------------------------

-- The lease is evaluated from the proofs rather than set by whoever recorded the last one.
-- A caller that could assert the state would be a caller that could assert reachability.
CREATE FUNCTION edge.evaluate_lease(p_tenant_id uuid, p_node_id uuid)
RETURNS edge.lease_state
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'pg_catalog', 'edge', 'public'
AS $$
DECLARE
    n edge.node%ROWTYPE;
    p edge.lease_policy%ROWTYPE;
    v_last_complete timestamptz;
    v_age    numeric;
    v_run    integer;
    v_state  edge.lease_state;
    v_reason text;
BEGIN
    SELECT * INTO n FROM edge.node
      WHERE tenant_id = p_tenant_id AND id = p_node_id AND status = 'active';
    IF NOT FOUND THEN
        RAISE EXCEPTION 'NODE_UNKNOWN: no active node % for this tenant', p_node_id
            USING ERRCODE = 'HS404';
    END IF;

    SELECT * INTO p FROM edge.lease_policy
      WHERE tenant_id = p_tenant_id AND outlet_id = n.outlet_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION
            'LEASE_POLICY_ABSENT: outlet % has no lease policy, so how long the cloud may '
            'go on forwarding without a proof is unanswered', n.outlet_id
            USING ERRCODE = 'HS409';
    END IF;

    -- A COMPLETE EXCHANGE IS BOTH DIRECTIONS VALID UNDER ONE CHALLENGE. This is the whole
    -- of FR-EDG-023 in one query, and it is why the challenge is shared.
    SELECT max(observed) INTO v_last_complete FROM (
        SELECT max(r.observed_at) AS observed
          FROM edge.reachability_proof r
         WHERE r.node_id = p_node_id
         GROUP BY r.challenge
        HAVING count(*) FILTER (WHERE r.valid) = 2
           AND count(DISTINCT r.direction) FILTER (WHERE r.valid) = 2) AS complete;

    v_age := CASE WHEN v_last_complete IS NULL THEN NULL
                  ELSE extract(epoch FROM (now() - v_last_complete)) END;

    -- HOW MANY COMPLETE EXCHANGES IN A ROW, counting back from the most recent and
    -- stopping at the first that was not complete.
    --
    -- ORDERED BY THE IDENTITY, NOT BY THE CLOCK. now() is the TRANSACTION timestamp in
    -- PostgreSQL, so every proof recorded in one transaction carries the same
    -- observed_at — and ordering by it then picks an arbitrary one as "most recent". The
    -- first version did that and reported a run of 3 immediately after a one-way failure,
    -- which is the lease staying live through exactly the event it exists to catch. The
    -- identity column is strictly increasing and cannot tie.
    SELECT count(*) INTO v_run FROM (
        SELECT bool_and(ok) OVER (ORDER BY last_id DESC ROWS UNBOUNDED PRECEDING) AS run_ok
          FROM (SELECT r.challenge, max(r.id) AS last_id,
                       count(*) FILTER (WHERE r.valid) = 2
                   AND count(DISTINCT r.direction) FILTER (WHERE r.valid) = 2 AS ok
                  FROM edge.reachability_proof r
                 WHERE r.node_id = p_node_id
                 GROUP BY r.challenge) AS exchanges) AS runs
     WHERE run_ok;

    IF v_age IS NULL THEN
        v_state := 'expired';
        v_reason := 'no complete exchange has ever been recorded for this node';
    ELSIF v_age > p.expire_after_seconds THEN
        v_state := 'expired';
        v_reason := format('%ss since the last complete exchange, and the lease expires '
                           'at %ss', round(v_age), p.expire_after_seconds);
    ELSIF v_age > p.degrade_after_seconds THEN
        v_state := 'degraded';
        v_reason := format('%ss since the last complete exchange, degraded at %ss and '
                           'expiring at %ss', round(v_age), p.degrade_after_seconds,
                           p.expire_after_seconds);
    ELSIF v_run < p.proofs_required_to_resume THEN
        -- COMING BACK IS SLOWER THAN GOING DOWN, on purpose. A flapping link produces
        -- occasional complete exchanges, and a lease that resumed on the first of them
        -- would flap with it.
        v_state := 'degraded';
        v_reason := format('%s consecutive complete exchange(s); %s are required before '
                           'the cloud may forward again', v_run, p.proofs_required_to_resume);
    ELSE
        v_state := 'live';
        v_reason := format('%s consecutive complete exchanges, the last %ss ago',
                           v_run, round(v_age));
    END IF;

    INSERT INTO edge.forwarding_lease (
        tenant_id, outlet_id, node_id, state, last_complete_exchange_at,
        consecutive_valid_exchanges, state_reason)
    VALUES (p_tenant_id, n.outlet_id, p_node_id, v_state, v_last_complete, v_run, v_reason)
    ON CONFLICT (node_id) DO UPDATE
       SET state = EXCLUDED.state,
           last_complete_exchange_at = EXCLUDED.last_complete_exchange_at,
           consecutive_valid_exchanges = EXCLUDED.consecutive_valid_exchanges,
           state_reason = EXCLUDED.state_reason,
           state_changed_at = CASE WHEN edge.forwarding_lease.state <> EXCLUDED.state
                                   THEN now() ELSE edge.forwarding_lease.state_changed_at END;

    RETURN v_state;
END;
$$;

COMMENT ON FUNCTION edge.evaluate_lease(uuid, uuid) IS
    'FR-EDG-023. Derives the lease from the proofs rather than taking a caller''s word: a '
    'caller that could assert the state would be a caller that could assert reachability. '
    'A complete exchange is BOTH directions valid under ONE challenge, which is why the '
    'challenge is shared.';

-- ---------------------------------------------------------------------------
-- 8. WHAT THE CLOUD ASKS BEFORE FORWARDING
-- ---------------------------------------------------------------------------

-- IT CHECKS THE CLOCK ITSELF, AND DOES NOT TRUST THE STORED STATE.
--
-- The obvious version reads forwarding_lease.state and returns whether it says 'live'.
-- That is correct for as long as something keeps calling evaluate_lease() — and the
-- moment the evaluator stops, the stored state stays `live` forever. A crashed worker
-- would leave the cloud forwarding into an outlet nobody has checked on since, which is
-- precisely the condition FR-EDG-023's 20-second expiry exists to end.
--
-- So the age is recomputed here against the outlet's own policy. A stale lease answers NO
-- without anybody having to notice it went stale, and a node nobody has ever evaluated —
-- no row at all — answers NO because a node nobody has ever reached is not reachable.
CREATE FUNCTION edge.may_forward(p_tenant_id uuid, p_node_id uuid)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path TO 'pg_catalog', 'edge', 'public'
AS $$
    SELECT COALESCE((
        SELECT l.state = 'live'
           AND l.last_complete_exchange_at IS NOT NULL
           AND extract(epoch FROM (now() - l.last_complete_exchange_at))
                 <= p.expire_after_seconds
          FROM edge.forwarding_lease l
          JOIN edge.lease_policy p
            ON p.tenant_id = l.tenant_id AND p.outlet_id = l.outlet_id
         WHERE l.node_id = p_node_id), false);
$$;

COMMENT ON FUNCTION edge.may_forward(uuid, uuid) IS
    'FR-EDG-023, FR-EDG-003. Whether the cloud may forward a command to this outlet right '
    'now. It recomputes the age rather than trusting the stored state: a lease that says '
    'live because nothing has evaluated it since the evaluator crashed is the exact '
    'condition the 20-second expiry exists to end. No lease row means NO — a node nobody '
    'has ever evaluated is a node nobody has ever reached.';

GRANT SELECT ON edge.lease_policy        TO hospitality_app;
GRANT SELECT ON edge.reachability_proof  TO hospitality_app;
GRANT SELECT ON edge.forwarding_lease    TO hospitality_app;
GRANT EXECUTE ON FUNCTION edge.proof_response(character, character, edge.proof_direction)
    TO hospitality_app;
GRANT EXECUTE ON FUNCTION edge.record_proof(
    uuid, uuid, character, edge.proof_direction, character, bigint, boolean, boolean)
    TO hospitality_app;
GRANT EXECUTE ON FUNCTION edge.evaluate_lease(uuid, uuid) TO hospitality_app;
GRANT EXECUTE ON FUNCTION edge.may_forward(uuid, uuid) TO hospitality_app;

-- ---------------------------------------------------------------------------
-- 9. THE NEW APPEND-ONLY TABLE, DECLARED
-- ---------------------------------------------------------------------------
--
-- edge.reachability_proof carries app.refuse_financial_mutation(), and 0042's assertion
-- requires every table that does to say WHY in app.append_only_tables(). The function is
-- REPLACED whole rather than extended, for the reason 0042 records: a replacement that
-- dropped an entry would put a table back outside the declaration without anybody editing
-- it. The financial half is still derived; only the named half grows.
CREATE OR REPLACE FUNCTION app.append_only_tables()
RETURNS TABLE (schema_name text, table_name text, reason text)
LANGUAGE sql STABLE
SET search_path TO 'pg_catalog', 'app', 'public'
AS $$
    SELECT n.nspname::text, c.relname::text, 'financial ledger'::text
      FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE c.relkind = 'r'
       AND app.financial_table_class(n.nspname, c.relname) = 'ledger'
     UNION ALL
    SELECT t.schema_name, t.table_name, t.reason
      FROM (VALUES
        ('pos', 'counter_order_entry',
         'which terminal an order was entered at, and by whom — a fact about what '
         'happened, not a row that is currently true'),
        ('edge', 'node_health_sample',
         'what a node reported about itself; a health history that can be edited is not '
         'evidence'),
        ('edge', 'node_admin_action',
         'administrative access to the node, which must survive the outage that makes '
         'the cloud audit ledger unreachable'),
        ('edge', 'reachability_proof',
         'FR-EDG-023: what each side proved about the other and when. This is the table '
         'an operator reads after an outage to find out which direction failed, and a '
         'reachability history that can be rewritten cannot answer that'),
        ('integration', 'sync_evidence',
         'FR-DAT-008C: append-only across replay and restart, including the deliveries '
         'the synchronization refused')
      ) AS t(schema_name, table_name, reason)
     ORDER BY 1, 2;
$$;

SELECT app.assert_append_only_guards_are_declared();
